AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  legal-rag-summarizer
  Serverless RAG application for summarizing legal PDFs (Async Architecture)

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Environment:
      Variables:
        OPENAI_API_KEY: !Ref OpenAiApiKey
        OPENAI_API_SECRET_ARN: !Ref OpenAiApiKeySecretArn
        REDIS_URL: !Ref RedisUrl
        S3_BUCKET_NAME: !Ref DocumentsBucket
        AWS_REGION: !Ref AWS::Region

Parameters:
  OpenAiApiKey:
    Type: String
    Description: OpenAI API Key (Optional if Secret ARN is provided)
    NoEcho: true
    Default: ""
  OpenAiApiKeySecretArn:
    Type: String
    Description: ARN of the OpenAI API Key Secret in Secrets Manager
    Default: ""
  RedisUrl:
    Type: String
    Description: Redis Connection String (e.g. redis://host:port)
    Default: redis://localhost:6379

Conditions:
  HasSecretArn: !Not [!Equals [!Ref OpenAiApiKeySecretArn, ""]]

Resources:
  # S3 Bucket for storing uploaded PDFs
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Use a predictable name to avoid circular dependency with Queue Policy
      BucketName: !Sub "legal-rag-documents-${AWS::AccountId}-${AWS::Region}"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ProcessingQueue.Arn

  # SQS Queue for processing jobs
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180

  # Queue Policy to allow S3 to send messages
  ProcessingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProcessingQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt ProcessingQueue.Arn
            Condition:
              ArnEquals:
                # Construct ARN manually to avoid GetAtt dependency
                aws:SourceArn: !Sub "arn:aws:s3:::legal-rag-documents-${AWS::AccountId}-${AWS::Region}"

  # API Function (Frontend)
  SummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.app.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        SummarizeApi:
          Type: Api
          Properties:
            Path: /summarize
            Method: post
        HealthCheck:
          Type: Api
          Properties:
            Path: /
            Method: get
        GetStatusApi:
          Type: Api
          Properties:
            Path: /status/{job_id}
            Method: get
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket

  # Worker Function (Backend)
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.worker.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 120
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessingQueue.Arn
            BatchSize: 1
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - !If
          - HasSecretArn
          - Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref OpenAiApiKeySecretArn
          - !Ref AWS::NoValue

Outputs:
  SummarizerApi:
    Description: "API Gateway endpoint URL for Prod stage for Summarizer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
